apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-kn000131
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: todo-api-kn000131
        image: peterpisut/todo-api
        imagePullPolicy: Always
        args:
        - nodemon
        - bin/www
        - --watch app.js
        - --watch routes
        env:
        - name: MONGO_CONNECTION_STRING
          value: mongodb://todo-db-kn000131.$(NAMESPACE).svc:27017
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst