apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-config.yaml
  - services.yaml
namespace: argo-rollouts
commonLabels:
  app: todo-api-kn000131
  group: todo-app
  template-compiler: kustomize
configurations:
  - varconfig.yaml
vars:
  - name: NAMESPACE
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: todo-api-kn000131
    fieldref:
     fieldPath: metadata.namespace