apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app-kn000131
    group: todo-app
    template-compiler: kustomize
  name: todo-app-kn000131
  namespace: argo-rollouts
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: todo-app-kn000131
    group: todo-app
    template-compiler: kustomize
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app-kn000131
    group: todo-app
    template-compiler: kustomize
  name: todo-app-kn000131
  namespace: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-kn000131
      group: todo-app
      template-compiler: kustomize
  template:
    metadata:
      labels:
        app: todo-app-kn000131
        group: todo-app
        template-compiler: kustomize
    spec:
      containers:
      - env:
        - name: PROXY_API_TARGET
          value: 10.44.1.28:9000
        image: peterpisut/todo-app
        imagePullPolicy: Always
        name: todo-app-kn000131
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: todo-app-kn000131
    group: todo-app
    template-compiler: kustomize
  name: todo-app-kn000131
  namespace: argo-rollouts
spec:
  backend:
    serviceName: todo-app-kn000131
    servicePort: 3000
