apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app-kn000131
    cluster: ocp-test
    group: todo-app
    template-compiler: kustomize
  name: todo-app-kn000131-dev
  namespace: devops-intern
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: todo-app-kn000131
    cluster: ocp-test
    group: todo-app
    template-compiler: kustomize
  type: ClusterIP
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: todo-app-kn000131
    cluster: ocp-test
    group: todo-app
    template-compiler: kustomize
  name: todo-app-kn000131-dev
  namespace: devops-intern
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app-kn000131
        cluster: ocp-test
        group: todo-app
        template-compiler: kustomize
    spec:
      containers:
      - env:
        - name: PROXY_API_TARGET
          value: http://todo-api-kn000131.devops-intern.svc:9000
        image: devops-cicd101-docker.artifactory.kasikornbank.com:8443/kn000131/todo-frontend
        imagePullPolicy: Always
        name: todo-app-kn000131
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecret:
      - name: image-pull-secret-kn000131
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todo-app-kn000131
    cluster: ocp-test
    group: todo-app
    template-compiler: kustomize
  name: todo-app-kn000131-dev
  namespace: devops-intern
spec:
  host: todo-app-kn000131-dev.devops-intern.apps.ocp-test.kasikornbank.com.172.30.183.115.nip.io
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: todo-app-kn000131-dev
    weight: 100
