apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db-kn000131
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: todo-db-kn000131
        image: peterpisut/todo-db
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP
        volumeMounts:
          - name: todo-data
            mountPath: /todo-data
      dnsPolicy: ClusterFirst
      volumes:
        - name: todo-data
          emptyDir: {}