apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-api-appz
    cluster: ocp-test
    group: todo-appz
    template-compiler: kustomize
  name: todo-api-appz
  namespace: devops-intern
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  selector:
    app: todo-api-appz
    cluster: ocp-test
    group: todo-appz
    template-compiler: kustomize
  type: ClusterIP
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    AppVersion: x-app-version-x
    KustomizeCommit: x-kustomize-commit-x
    app: todo-api-appz
    cluster: ocp-test
    group: todo-appz
    template-compiler: kustomize
  name: todo-api-appz
  namespace: devops-intern
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-api-appz
        cluster: ocp-test
        group: todo-appz
        template-compiler: kustomize
    spec:
      containers:
      - args:
        - nodemon
        - bin/www
        - --watch app.js
        - --watch routes
        env:
        - name: MONGO_CONNECTION_STRING
          value: mongodb://todo-db-appz.devops-intern.svc:27017
        image: devops-cicd101-docker.artifactory.kasikornbank.com:8443/kn000131/todo-appz/api
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: todo-api-appz
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: image-pull-secret-kn000131
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todo-api-appz
    cluster: ocp-test
    group: todo-appz
    template-compiler: kustomize
  name: todo-api-appz
  namespace: devops-intern
spec:
  host: todo-api-appz-appz.devops-intern.apps.ocp-test.kasikornbank.com.172.30.183.115.nip.io
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: todo-api-appz
    weight: 100
