apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: "2020-06-19T10:33:59Z"
  generation: 1
  labels:
    app: todo-db-kn000131
  name: todo-db-kn000131
  namespace: devops-intern
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: todo-db
    app: todo-db-kn000131
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: todo-db
        app: todo-db-kn000131
    spec:
      containers:
      - image: devops-cicd101-docker.artifactory.kasikornbank.com:8443/kn000131/todo-db:v6
        imagePullPolicy: Always
        name: todo-db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /todo-data
          name: todo-volume
      volumes:
      - name: todo-volume
        emptyDir: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: image-pull-secret-kn000131
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
