apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-api-kn000131
    group: todo-app
    template-compiler: kustomize
  name: todo-api-kn000131
  namespace: argo-rollouts
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  selector:
    app: todo-api-kn000131
    group: todo-app
    template-compiler: kustomize
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-api-kn000131
    group: todo-app
    template-compiler: kustomize
  name: todo-api-kn000131
  namespace: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api-kn000131
      group: todo-app
      template-compiler: kustomize
  template:
    metadata:
      labels:
        app: todo-api-kn000131
        group: todo-app
        template-compiler: kustomize
    spec:
      containers:
      - args:
        - nodemon
        - bin/www
        - --watch app.js
        - --watch routes
        env:
        - name: MONGO_CONNECTION_STRING
          value: mongodb://todo-db-kn000131.argo-rollouts.svc.cluster.local:27017
        image: peterpisut/todo-api
        imagePullPolicy: Always
        name: todo-api-kn000131
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
