apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-db-kn000131
    group: todo-app
    template-compiler: kustomize
  name: todo-db-kn000131
  namespace: argo-rollouts
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    app: todo-db-kn000131
    group: todo-app
    template-compiler: kustomize
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-db-kn000131
    group: todo-app
    template-compiler: kustomize
  name: todo-db-kn000131
  namespace: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db-kn000131
      group: todo-app
      template-compiler: kustomize
  template:
    metadata:
      labels:
        app: todo-db-kn000131
        group: todo-app
        template-compiler: kustomize
    spec:
      containers:
      - image: peterpisut/todo-db
        imagePullPolicy: Always
        name: todo-db-kn000131
        ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP
        volumeMounts:
        - mountPath: /todo-data
          name: todo-data
      dnsPolicy: ClusterFirst
      volumes:
      - emptyDir: {}
        name: todo-data
