apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: todo-app-appz
  labels:
    AppVersion: x-app-version-x
    KustomizeCommit: x-kustomize-commit-x
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: todo-app-appz
        image: devops-cicd101-docker.artifactory.kasikornbank.com:8443/kn000131/todo-appz/react
        imagePullPolicy: Always
        env:
          - name: PROXY_API_TARGET
            value: http://todo-api-appz.devops-intern.svc:9000

        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: image-pull-secret-kn000131
