apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: todo-app-appz
spec:
  host: todo-app-appz.$(NAMESPACE).apps.$(LABEL_CLUSTER).kasikornbank.com.172.30.183.115.nip.io
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: todo-app-appz
    weight: 100
