apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-kn000131
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: todo-app-kn000131
        image: peterpisut/todo-app
        imagePullPolicy: Always
        env:
          - name: PROXY_API_TARGET
            value: todo-api-kn000131.$(NAMESPACE).svc.cluster.local:9000
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst