apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todo-app-kn000131
spec:
  rules:
  - host: $(SERVICE_NAME).$(NAMESPACE).svc.cluster.local
    http:
      paths:
      - path: /*
        backend:
          serviceName: todo-api-kn000131
          servicePort: 9000

